# Exercise 2.B Cleaning up Data

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [9]:
df = pd.read_csv("test_data.csv")

In [10]:
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Filtering a DataFrame

In [12]:
# rows where age is > 18

df[df["Age"] > 18]

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [13]:
# rows where score is > than 50 and < 100

df[(df["Score"] > 50) & (df["Score"] < 100)]

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [14]:
df_cleaned = df.drop(df[df["Score"] < 0].index)

In [15]:
df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [16]:
# Remove city column. Axis 1 tells pandas to drop a column rather than a row

df_cleaned = df_cleaned.drop("City", axis=1)

In [17]:
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [19]:
# Replace missing Age value with the mean Age 

df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())

df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [20]:
# Replace any score value of 0 with the mean score 

mean_score = df_cleaned["Score"].mean()

df_cleaned["Score"] = df_cleaned["Score"].replace(0, mean_score)

In [21]:
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [22]:
# Remove remaining rows containing NaN values 

df_cleaned = df_cleaned.dropna()

In [23]:
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [24]:
# Use ID as the index and remove the ID column
df_cleaned = df_cleaned.set_index("ID")

In [25]:
df_cleaned

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0